quarkus:
  http:
    cors: true

  log:
    level: DEBUG
    category: 
      io.resys:
        level: DEBUG

"%prod":
  quarkus:

"%dev":
  quarkus:
    log:
      level: DEBUG
      category: 
        io.github.jocelynmutso:
          level: DEBUG
