quarkus:
  http:
    cors: true

  log:
    level: DEBUG
    category: 
      io.resys:
        level: DEBUG

  zoe-ide:
    server-path: not-ready

  zoe-ide-services:
    service-path: /q/zoe-ide-services
    db:
      db-name: test-assets
      connection-url: mongodb://appUser:123456@localhost:27017/test-assets?authSource=test-assets
    repo:
      repo-name: test-assets

"%prod":
  quarkus:

"%dev":
  quarkus:
    log:
      level: DEBUG
      category: 
        io.github.jocelynmutso:
          level: DEBUG
        io.resys:
          level: DEBUG